### ISSUE TITLE
None attestation statement format should not be accepted when Attestation Conveyance Preference DIRECT/INDIRECT was used

### ISSUE THREAD

**Issue by gregory-demay** [Yubico/java-webauthn-server#100]
Hi 

First thanks a lot for your work on this library! 
During our internal security review, we stumble upon the following behavior which we think is not correct (the WebAuthn spec. in this area is not very explicit and so whether it really is a bug in the library might be up for discussion).

### Setup

- Library: com.yubico:webauthn-server-core:1.7.0

### Observed Behavior

1. Relying Party produces a challenge for registration with Attestation Conveyance Preference DIRECT (or INDIRECT)
2. (Emulated) FIDO authenticator produces an answer with an empty attestation statement (attestation format NONE)
3. Response is accepted by the library (when calling `com.yubico.webauthn.RelyingParty#finishRegistration`)

### Expected Behavior

- Response from authenticator with attestation format NONE is rejected and produces a `com.yubico.webauthn.exception.RegistrationFailedException`.

### Reasoning
According to the WebAuthn specification regarding [None Attestation Format](https://www.w3.org/TR/webauthn-1/#none-attestation)

> The none attestation statement format is used to replace any authenticator-provided attestation statement **when a WebAuthn Relying Party indicates it does not wish to receive attestation information**, see §5.4.6 Attestation Conveyance Preference Enumeration (enum AttestationConveyancePreference).

The definition of an AttestationConveyancePreference is a bit fuzzy, since whether the preference is enforced, is unclear.
According to [Attestation Conveyance Preference Enumeration](https://www.w3.org/TR/webauthn-1/#attestation-convey)
> **direct**
>This value indicates that the Relying Party **wants to receive the attestation statement as generated by the authenticator**.

Overall, my understanding of the specification is that NONE attestation format should only be accepted during registration when Attestation Conveyance Preference was NONE.

**Comment by emlun** [comment]
Hi! Thank you for your review and comments. Yes, this is intentional. It is perfectly plausible that an RP may request attestation information by setting the attestation conveyance preference to `direct`, but still accept registrations with or without attestation information. This would allow the RP to, for example, inform its users about compromised authenticators where such information is available, but without unnecessarily restricting the user's choice of authenticator. Therefore this library exposes two orthogonal options:

- [`attestationConveyancePreference`](https://developers.yubico.com/java-webauthn-server/JavaDoc/webauthn-server-core/latest/com/yubico/webauthn/RelyingParty.RelyingPartyBuilder.html#attestationConveyancePreference(com.yubico.webauthn.data.AttestationConveyancePreference)) which gets sent as the [`attestation`](https://www.w3.org/TR/webauthn-1/#dom-publickeycredentialcreationoptions-attestation) option in the registration ceremony, and
- [`allowUntrustedAttestation`](https://developers.yubico.com/java-webauthn-server/JavaDoc/webauthn-server-core/latest/com/yubico/webauthn/RelyingParty.RelyingPartyBuilder.html#allowUntrustedAttestation(boolean)) which controls whether the library will refuse registrations that do not include attestation from a trusted source, as configured via the [`metadataService`](https://developers.yubico.com/java-webauthn-server/JavaDoc/webauthn-server-core/latest/com/yubico/webauthn/RelyingParty.RelyingPartyBuilder.html#metadataService(com.yubico.webauthn.attestation.MetadataService)) option.

So if the RP wants to be strict about attestation, it would configure a `metadataService` and set `allowUntrustedAttestation` to false.

The [`RegistrationResult`](https://developers.yubico.com/java-webauthn-server/JavaDoc/webauthn-server-core/latest/com/yubico/webauthn/RegistrationResult.html) object also conveys the attestation type and an "attestation trusted" flag, in case the caller wants to apply more fine-grained logic. The library doesn't make any changes to a database, so it is ultimately up to the caller whether to accept the registration anyway.

Does that address your concerns?

**Comment by emlun** [comment]
While I don't think we need any change to the library logic, this did make me notice that the documentation for the above two options should reference each other. Something like: "If you set the `attestationConveyancePreference` option, you probably want to set `allowUntrustedAttestation` too".

**Comment by gregory-demay** [comment]
Hi! Thanks for answering so promptly. Sounds like `allowUntrustedAttestation` was definitively the missing piece, thanks for pointing this out!. I will look at it in more details in the next few days and come back to you or close the issue as needed.

**Comment by gregory-demay** [comment]
That closes the issue for us, thanks!
