### ISSUE TITLE
Authenticate doesn't work on Chrome

### ISSUE THREAD

**Issue by rgerganov** [Yubico/java-webauthn-server#12]
Steps to reproduce:
1. Register a new account
2. Try to authenticate

Server response:
```
{
  "messages": [
    "Assertion failed!",
    "java.lang.IllegalArgumentException: User handle ByteArray() does not own credential ByteArray(3dGcBiyN73KXMGzM+d26w2B4wifi5pH0qqwQp7pGhRHD1Mn8f4oJuPrigPR7akpAGnrpNiGUkjKOJ1ZzSXJ78Q==)"
  ]
}
```
I am using Chrome 70.0.3538.77 and verified that the issue doesn't exist on Firefox. The root cause for this is that the `userHandle` returned by the authenticator is an empty ArrayBuffer and Chrome evaluates this as `true` whereas on Firefox it is `null` which is evaluated as `false`.

The fix would be to either handle empty array buffers for `userHandle` in the backend or add more checks in `webauthn.js` to prevent sending empty array buffers in the first place.

**Comment by emlun** [comment]
Correct. This is a [bug in Chrome][bug] and will not be fixed in the example app client script, and certainly not in the server-side library code since the empty byte array is a valid value for the user handle. You're welcome to work around it as you describe in your own application code.

I'll add this to a (new) list of known issues in the project README. Thanks!

[bug]: https://bugs.chromium.org/p/chromium/issues/detail?id=847878
