### ISSUE TITLE
RegistrationResult could not have a public builder?

### ISSUE THREAD

**Issue by rochards** [Yubico/java-webauthn-server#134]
Hello,

Why is not allowed `RegistrationResult` class have a public builder? It would be easier to set optional attributes, like
```
RegistrationResult.builder()
                    .setTransports(...)
                    .build();
```

to save additional information to database.

Thank you.

**Comment by emlun** [comment]
Hi!

The straightforward answer is that it's intended to represent `The result of a call to RelyingParty#finishRegistration(FinishRegistrationOptions)`, to quote the JavaDoc, and not really intended to be an object you directly store in your database. So that's why the builder is hidden.

As for the specific question about credential transports, the next release will automatically pass transports through from `PublicKeyCredential` to the `RegistrationResult.keyId.transports` returned from `RelyingParty.finishRegistrationSteps()`. Would that cover your needs?

**Comment by rochards** [comment]
Yes! That's exactly what I need for my application. That would be great! Thank you!
