### ISSUE TITLE
No value present for Yubico Security Key on finishAssertion

### ISSUE THREAD

**Issue by krystianity** [Yubico/java-webauthn-server#181]
Hi there, thank you for this lib.

It works really well for me so far using TouchID or Apple Watch for registration and authentication, after following the documentation in the README.

However I am having issues with my Yubico Security Key, while testing I have registered it once and authentication worked a few times. After deleting it from the app and re-registering for another test round, the authentication seems to be broken.
I can see that my CredentialRepository finds the handle as well as the credential, however the `relyingParty.finishAssertion` steps fails with `No value present` (see stack down below).

# Error stack:

```txt
java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.get(Optional.java:148)
	at com.yubico.webauthn.FinishAssertionSteps$Step0.lambda$new$0(FinishAssertionSteps.java:127)
	at java.base/java.util.Optional.orElseGet(Optional.java:369)
	at com.yubico.webauthn.FinishAssertionSteps$Step0.<init>(FinishAssertionSteps.java:126)
	at com.yubico.webauthn.FinishAssertionSteps.begin(FinishAssertionSteps.java:75)
	at com.yubico.webauthn.FinishAssertionSteps.run(FinishAssertionSteps.java:79)
	at com.yubico.webauthn.RelyingParty.finishAssertion(RelyingParty.java:504)
       ...
```

# Version info:

- macOS Monterey 12.1, M1 Pro
- Firefox 98.0 / Chrome 99.0
- Yubico Security Key Series (Firmware 4.x.x)
- openjdk 11.0.13
- webauthn-server-core 1.12.3-RC1
- jackson-dataformat-cbor 2.11.0

**Comment by emlun** [comment]
Hi! Thanks, this pointed out a logic bug in `finishAssertion` which is now fixed in pre-release [`1.12.3-RC2`](https://github.com/Yubico/java-webauthn-server/releases/tag/1.12.3-RC2). I think it will still throw an exception, but it will be a much better error message that explains what's going wrong. Did you perhaps register the Security Key with `.residentKey(PREFERRED)` or `.residentKey(REQUIRED)`, and not set `StartAssertionOptions.username` when initiating the authentication?

**Comment by krystianity** [comment]
Thanks for the quick reply @emlun.
FYI initially tried with 1.12.4-RC1 that still gives `No value present exception`.

With 1.12.3-RC2 I am now seeing `java.lang.IllegalArgumentException: At least one of username and user handle must be given; none was.`

To my knowledge I was always providing a userHandle and residentKey was never used (always sticked to default builder settings / README examples).

**Comment by krystianity** [comment]
Hmm... seems like either request.username or response.userhandle is required.

```
public void validate() {
            ExceptionUtil.assure(FinishAssertionSteps.this.request.getUsername().isPresent() || ((AuthenticatorAssertionResponse)FinishAssertionSteps.this.response.getResponse()).getUserHandle().isPresent(), "At least one of username and user handle must be given; none was.", new Object[0]);
```

Not sure why it breaks in the Yubico Security Key case, since I am always building the .get() request like this:

```
final AssertionRequest request = relyingParty.startAssertion(StartAssertionOptions.builder()
            .userHandle(userHandle)
            .build());
```

That will always result in request.username being not present?
The README makes it seem like switching between username() or .userHandle() for StartAssertionOptions makes no difference.

**Comment by emlun** [comment]
Oooh, I think I see what's going on. The user handle in `StartAssertionOptions` doesn't get passed through to `AssertionRequest`, and `finishRegistration` only looks for the user handle in the `AuthenticatorAssertionResponse` where it's null for server-side credentials. It probably works with the Apple devices because they always store and return the user handle, while the Security Key does not (because it doesn't store any data except for discoverable keys). I'll get on a fix, thanks for the report and for your patience in sorting this out!

> FYI initially tried with 1.12.4-RC1 that still gives `No value present exception`.

Yeah, the `1.12.3`, `1.12.4` and `2.0.0` releases are all happening in parallel right now and I haven't ported this fix forward to the latter two yet.

**Comment by emlun** [comment]
Should be fixed now in release [`1.12.3-RC3`](https://github.com/Yubico/java-webauthn-server/releases/tag/1.12.3-RC3), please try it out!

**Comment by krystianity** [comment]
Awesome, it works now - thanks :)

**Comment by emlun** [comment]
Great, thanks again for the report! We'll likely promote the RC3 to a proper non-RC release in about a week or two.
