### ISSUE TITLE
Work with exclude credentials and question about AAGUID

### ISSUE THREAD

**Issue by igorlogvin** [Yubico/java-webauthn-server#186]
Hello developers!
Can you please explain exactly how java-webauthn-core works with excludeCredentials? I set exclude on id, but when re-creating PublicKeyCredentialCreationOptions, shouldn't there be an error that options have already been created for that id? Example here:
```
"excludeCredentials": [
            {
                "type": "public-key",
                "id": "AAAAAAAAADM",
                "transports": []
            }
        ]
```

And i have another question.
How java-webauthn-server detects if device registered already? Should i use AAGUID for validate if device exists?
If i will use AAGUID for validation on "finish 
registration" ceremony, can i assume that this GUID is unique per device and not per device model? I mean, if I have 2 different iPhones of the same model, will they have different AAGUIDs?

Thanks for yours attention.

**Comment by emlun** [comment]
> Can you please explain exactly how java-webauthn-core works with excludeCredentials?

`excludeCredentials` is set automatically by `RelyingParty.startRegistration()`. It is set to the result of calling the `getCredentialIdsForUsername(String)` method of the provided `CredentialRepository` implementation.

> I set exclude on id, but when re-creating PublicKeyCredentialCreationOptions, shouldn't there be an error that options have already been created for that id?

Sorry, I don't understand the question. What do you mean by "set exclude on id"? And what error do you mean should appear?

> How java-webauthn-server detects if device registered already?

The server-side code does not and cannot, that is done on the client side using `excludeCredentials`. The client and authenticator will show an error if the user tries to use an authenticator that already has one of the credentials listed in `excludeCredentials`, and tell the user to use a different authenticator instead.

For example, it is perfectly valid for a user to register the same authenticator to two different accounts (as two different credentials). The server would normally not know that the two credentials are on the same authenticator.

> Should i use AAGUID for validate if device exists? If i will use AAGUID for validation on "finish registration" ceremony, can i assume that this GUID is unique per device and not per device model?

No, the AAGUID identifies an authenticator model, not an individual authenticator. You don't need to implement logic to check if an authenticator is already registered, you just need to implement the `CredentialRepository` methods as specified in their JavaDoc.

**Comment by igorlogvin** [comment]
Hi, Emil ! Thanks for your answer.
About "set exclude on id". I mean, if I don't force excludeCredentials, then I manage to create the signature again for the same user by same username. The same behavior if I use forced installation in the builder according to the example:
`PublicKeyCredentialCreationOptions credentialCreation = relyingParty.startRegistration(buildStartRegistrationOptions(startRegistrationRequest))
                 .toBuilder()
                 .timeout(6000)
                 .attestation(AttestationConveyancePreference.DIRECT)
                 .excludeCredentials(
                         Collections.singleton(
                                 PublicKeyCredentialDescriptor.builder()
                                         .id(new ByteArray(BytesUtil.longToBytes(startRegistrationRequest.getUserId())))
                                         .transports(Collections.emptySet())
                                         .build()
                         )
                 )
                 .build();`

Apparently I do not fully understand at what stage excludeCredentials is checked. Maybe at the navigator.credentials.get() stage? 


Next, about AAGUID. 
My task is to display to the user in the personal account menu information about which device he already has registered signatures from. For example, "You have the following signatures: Apple iPhone, Windows 10, Samsung." I planned to additionally save information from `window.navigator.userAgent` and AAGUID. This would allow the `window.navigator.userAgent` data to be assigned to a specific AAGUID. So my question was whether the AAGUID is unique to a particular device or is it only unique to the model of this device. In the documentation itself they write:

> Additionally, each authenticator has an AAGUID, which is a 128-bit identifier indicating the type (e.g. make and model) of the authenticator. The AAGUID MUST be chosen by the manufacturer to be identical across all substantially identical authenticators made by that manufacturer, and different (with high probability) from the AAGUIDs of all other types of authenticators. The AAGUID for a given type of authenticator SHOULD be randomly generated to ensure this. The Relying Party MAY use the AAGUID to infer certain properties of the authenticator, such as certification level and strength of key protection, using information from other sources.


That is, we can say that AAGUID contains information about the model and unique information of this device?


> > Can you please explain exactly how java-webauthn-core works with excludeCredentials?
> 
> `excludeCredentials` is set automatically by `RelyingParty.startRegistration()`. It is set to the result of calling the `getCredentialIdsForUsername(String)` method of the provided `CredentialRepository` implementation.
> 
> > I set exclude on id, but when re-creating PublicKeyCredentialCreationOptions, shouldn't there be an error that options have already been created for that id?
> 
> Sorry, I don't understand the question. What do you mean by "set exclude on id"? And what error do you mean should appear?
> 
> > How java-webauthn-server detects if device registered already?
> 
> The server-side code does not and cannot, that is done on the client side using `excludeCredentials`. The client and authenticator will show an error if the user tries to use an authenticator that already has one of the credentials listed in `excludeCredentials`, and tell the user to use a different authenticator instead.
> 
> For example, it is perfectly valid for a user to register the same authenticator to two different accounts (as two different credentials). The server would normally not know that the two credentials are on the same authenticator.
> 
> > Should i use AAGUID for validate if device exists? If i will use AAGUID for validation on "finish registration" ceremony, can i assume that this GUID is unique per device and not per device model?
> 
> No, the AAGUID identifies an authenticator model, not an individual authenticator. You don't need to implement logic to check if an authenticator is already registered, you just need to implement the `CredentialRepository` methods as specified in their JavaDoc.

**Comment by emlun** [comment]
> sorry, I haven't learned yet how to beautify code block

No worries! I edited your comment to add code block formatting, you can go into editing mode yourself to see the markup.

> About "set exclude on id". I mean, if I don't force excludeCredentials, then I manage to create the signature again for the same user by same username. The same behavior if I use forced installation in the builder according to the example:

Ok, a couple of things here:

- I recommend setting `.attestationConveyancePreference(AttestationConveyancePreference.DIRECT)` in `RelyingPartyBuilder` instead of after calling `startRegistration()`, unless you need to override that setting on a per-request basis.
- Likewise, you should set the timeout in `StartRegistrationOptionsBuilder` instead. Also, 6 seconds is probably far too short, and it's likely that browsers will override this setting and set it to something like 30 seconds instead.
- `startRegistrationRequest.getUserId()` is a [user handle](https://www.w3.org/TR/2021/REC-webauthn-2-20210408/#user-handle), but `PublicKeyCredentialDescriptor.id` needs to be a [credential ID](https://www.w3.org/TR/2021/REC-webauthn-2-20210408/#credential-id).
  - Again, if your `CredentialRepository` implementation's `getCredentialIdsForUsername` method returns all credential IDs registered for the given user, then `excludeCredentials` will be set automatically, so you shouldn't need to override `excludeCredentials`. During authentication, `allowCredentials` is set in the same way. If those aren't working, then there's probably something wrong in your implementation of `getCredentialIdsForUsername`.

> Apparently I do not fully understand at what stage excludeCredentials is checked. Maybe at the navigator.credentials.get() stage?

`excludeCredentials` is checked in `navigator.credentials.create()` (note: `create`, not `get`), and typically the browser will instruct the user to use a different authenticator if they try to use one that already has one of the credentials in `excludeCredentials`.

> That is, we can say that AAGUID contains information about the model and unique information of this device?

No, AAGUID is not unique per device. It only identifies an authenticator model, and will be the same for all authenticators of that model.

> My task is to display to the user in the personal account menu information about which device he already has registered signatures from. For example, "You have the following signatures: Apple iPhone, Windows 10, Samsung."

For this you might need to consult an external data source, for example the [FIDO Metadata Service (MDS)](https://fidoalliance.org/metadata/). The AAGUID itself is just a random ID, it doesn't itself contain product names or the like. You might be able to find some in the attestation certificates, but it's not likely to be as neat as you probably want it. Alternatively you could build your own database of AAGUIDs and product names, but that's likely to fail as new models and sometimes versions are added.

The upcoming 2.0 release of this library will come with [integrated support for the FIDO MDS](https://github.com/Yubico/java-webauthn-server/blob/6bb82b76223ebc00defbe61a548ca742d4f7f04a/webauthn-server-attestation/README.adoc), in case you need it.

> Also, should I manage the value of transports in `allowCredentials `and `excludeCredentials `myself?

You should store the `RegistrationResult.getKeyId()` object in your database, and then return it in the `getCredentialIdsForUsername` method of your `CredentialRepository` implementation. You should not edit the values in between.

Note that in order for the transports to be picked up, you need to call `PublicKeyCredential.response.getTransports()` after a successful `navigator.credentials.create()`, as noted in the [getting started guide](https://github.com/Yubico/java-webauthn-server/tree/a92c71a896773ec37be9c177984e5518c02723fc#3-registration). If you use GitHub's [webauthn-json](https://github.com/github/webauthn-json) library, it will do this for you automatically.

---

I hope that answers at least some of your questions! You're very welcome to continue with any more, or remaining, questions you have.

**Comment by igorlogvin** [comment]
> No worries! I edited your comment to add code block formatting, you can go into editing mode yourself to see the markup.

Thanks for that! You are amazing :)

> I recommend setting .attestationConveyancePreference(AttestationConveyancePreference.DIRECT) in RelyingPartyBuilder instead of after calling startRegistration(), unless you need to override that setting on a per-request basis.

Okay, i try it.

> Likewise, you should set the timeout in StartRegistrationOptionsBuilder instead. Also, 6 seconds is probably far too short, and it's likely that browsers will override this setting and set it to something like 30 seconds instead.

Yes, in my code it's just for test. This is not the final version of the code as I am still learning about this library.

> `startRegistrationRequest.getUserId()` is a [user handle](https://www.w3.org/TR/2021/REC-webauthn-2-20210408/#user-handle), but PublicKeyCredentialDescriptor.id needs to be a [credential ID](https://www.w3.org/TR/2021/REC-webauthn-2-20210408/#credential-id)

Oh, thanks for that tip! Apparently I missed this moment.

> No, AAGUID is not unique per device. It only identifies an authenticator model, and will be the same for all authenticators of that model.

Okay, now I understand.

> The upcoming 2.0 release of this library will come with [integrated support for the FIDO MDS](https://github.com/Yubico/java-webauthn-server/blob/6bb82b76223ebc00defbe61a548ca742d4f7f04a/webauthn-server-attestation/README.adoc), in case you need it.

Can you please tell me when version 2.0 is planned to be released? Perhaps in my system they want to upgrade and use the services of FIDO MDS.

And i have another questions (sorry for that):

1. My system has a separate between the storage of data such as challenge and credentialId. They want to generate challenge on their side. But I see that in this library you are already generating challenge for registration and attestation ceremonies. Can I replace the challenge from `startRegistration/startAssertion` with my own in the same format before giving options to `navigator.credentials.create()`? This is necessary for the adjacent system to store such data on itself, since my system is basically proxying between frontend, java-webauthn-core and them.
2. Let's say we had a successful startRegistration ceremony. The next day, we log in. My team wants to use the same challenge for the assertion that was generated for the registration ceremony. That is, startRegistration passed with challenge `5gygfoCqbEMibRb8PI820WkBjIAKj_-xYj6cVvSqt3o`. Can we set the same challenge for startAssertion as well? 

- If yes, then to enter I need, before executing startAssertion, go to the adjacent system and get that challenge. They want to use the credentialId as a request parameter. This begs the question, can we get the credentialId BEFORE finishAssertion is fired?

**Comment by emlun** [comment]
> Can you please tell me when version 2.0 is planned to be released? Perhaps in my system they want to upgrade and use the services of FIDO MDS.

The release is planned for April 26th, but the `2.0.0-RC1` pre-release version is already available on Maven Central if you want to try it. You can find the documentation for the FIDO MDS module by the link I posted above, and the documentation for the core module [here](https://github.com/Yubico/java-webauthn-server/tree/6bb82b76223ebc00defbe61a548ca742d4f7f04a) (it's mostly the same as for 1.x if you don't already have code that needs to migrate).

> 1. My system has a separate between the storage of data such as challenge and credentialId. They want to generate challenge on their side. [...] Can I replace the challenge from `startRegistration/startAssertion` with my own in the same format before giving options to `navigator.credentials.create()`?

Yes, you can use `PublicKeyCredentialCreationOptions.toBuilder().challenge(/* ... */).build()` to override the challenge.

---

> 2. Let's say we had a successful startRegistration ceremony. The next day, we log in. My team wants to use the same challenge for the assertion that was generated for the registration ceremony. That is, startRegistration passed with challenge `5gygfoCqbEMibRb8PI820WkBjIAKj_-xYj6cVvSqt3o`. Can we set the same challenge for startAssertion as well?

# ***NEVER, ABSOLUTELY DO NOT DO THIS.***

Sorry, I mean no offense to you or your colleagues, I just want to make this very clear.

This will destroy the replay prevention and completely undermine security. If an eavesdropper can record one authentication ceremony, then they can trigger a new authentication ceremony and replay the same signature. Since the challenge is the same, the old signature will also be valid for the fraudulent authentication.

***DO NOT DO THIS.*** You MUST tell your colleagues that reusing the challenge is ***COMPLETELY INSECURE***. See also the [§13.4.3. Cryptographic Challenges](https://www.w3.org/TR/2021/REC-webauthn-2-20210408/#sctn-cryptographic-challenges) security consideration in the spec. Every challenge MUST be unique, MUST be unpredictable, and MUST be completely unrelated to other challenges. I also recommend that challenges expire after a short time (~5-15 minutes) and that `RelyingParty.finishAssertion()` may be attempted only once for each challenge - so if `finishAssertion()` fails, then the challenge for that request is invalidated and the authentication ceremony has to start over.

**Comment by igorlogvin** [comment]
Emil, thanks for answer.

> NEVER, ABSOLUTELY DO NOT DO THIS.

It's good that we discussed this.

Okay, You really help me a lot in my task.

I hope it's will a final question from my side. We save the credentialId to the database. How can we get the credentialId before the `startAssertion` fires? This is for my system to go to another system with this credentialId and request a challenge code for sign-in?

**Comment by emlun** [comment]
> I hope it's will a final question from my side. We save the credentialId to the database. How can we get the credentialId before the `startAssertion` fires?

Typically you would do this by asking the user for a username and password first, and then look up that user's credential IDs and do WebAuthn authentication as a second step.

> For example, a user has 5 signatures stored in our database. But we need a specific signature for the current Sign In. Is it realistic to get the credentialId before navigator.credentials.get() is processed?

By "signatures", do you mean "public keys"? Then yes, you could set `allowCredentials` to contain only one of the credential IDs, and then only that key may be used for that authentication operation. But...

> Or if we get all the signatures and put them in allowCredentials and if there are no such signatures in the authenticator, then the authenticator will tell us about it and don't worry?

Yes, unless you have some reason to prefer one particular key, you can list all of the user's credentials in `allowCredentials`. The user's browser and authenticator(s) will work together to figure out which to use, if any. If none of those keys are available, the `navigator.credentials.get()` call just fails.

In fact, this is the default behaviour - `RelyingParty.startAuthentication()` will automatically set `allowCredentials` to a list of all the user's credentials if you set the `username` or `userHandle` in `StartRegistrationOptions` (assuming a correct implementation of `CredentialRepository.getCredentialIdsForUsername`).

**Comment by igorlogvin** [comment]
Thanks, Emil!

> In fact, this is the default behaviour - RelyingParty.startAuthentication() will automatically set allowCredentials to a list of all the user's credentials if you set the username or userHandle in StartRegistrationOptions (assuming a correct implementation of CredentialRepository.getCredentialIdsForUsername).

Yep, i got it. 

Another question after 3 days. Do this library written via Level 2 of documentation https://www.w3.org/TR/2021/REC-webauthn-2-20210408 ?


In response of `navigator.credentials.get()` we have `signature` field. Does we need validate him value additionally after finishAssertion will works?

**Comment by emlun** [comment]
> Another question after 3 days. Do this library written via Level 2 of documentation https://www.w3.org/TR/2021/REC-webauthn-2-20210408 ?

Yes, the implementation is based on that spec version. There are a couple of deprecated APIs in 1.x that will soon be removed in 2.0, but they will be marked as such with `@Deprecated` when there is a pre-emptive migration path available.

> In response of `navigator.credentials.get()` we have `signature` field. Does we need validate him value additionally after finishAssertion will works or we just should save him to DB and forget about him?

`RelyingParty.finishAssertion()` will verify the signature and validate all the response data as specified in the [RP Operations spec](https://www.w3.org/TR/2021/REC-webauthn-2-20210408/#sctn-verifying-assertion). So no, you do not need to verify the signature yourself. Many applications likely don't need to store the signatures either, but for a bank application I can certainly see that being useful (or even required by law).

**Comment by igorlogvin** [comment]
Okay, thanks, Emil!
Now it's all questions from my side.
You very helped me a lot.
Now, i'm closing this issue. Have a nice day!
