### ISSUE TITLE
remove class name duplication

### ISSUE THREAD

**Issue by remmeier** [Yubico/java-webauthn-server#20]
various classes like AssertionRequest are duplicated both in the demo application and thewebauthn-server-core library. This is rather confusing. Would be great if they could be named differently and specify their purpose, or better, be removed in favor of reusable ones from the library to limit the effort to implement such a relay (currently rather high in terms of lines of code).

**Comment by emlun** [comment]
Hi! Thanks, this is now fixed on master. I won't make a release for this since this only changes the demo and not the library.

**Comment by emlun** [comment]
The reason the library doesn't provide a reusable `AssertionRequest` wrapper is that the contents of that wrapper would be highly application specific. I renamed the demo's wrapper class to `AssertionRequestWrapper`.

The `RegistrationResult` class was duplicated only because it cannot be constructed outside the `com.yubico.webauthn` package, and I needed to hack around that to enable registration via the U2F API in the demo (to exercise the `appid` extension). I've now eliminated the need to construct that particular class, and replaced the duplicate class with one named `U2fRegistrationResult` instead.
