### ISSUE TITLE
clientExtensionResults mandatory?

### ISSUE THREAD

**Issue by zafodB** [Yubico/java-webauthn-server#21]
The method `PublicKeyCredential.parseRegistrationResponseJson(responseJson)` fails if the `responseJson` doesn't contain clientExtensionResults with error:

`com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of com.yubico.webauthn.data.PublicKeyCredential, problem: clientExtensionResults is marked @NonNull but is null`

Is this desired behaviour? My understanding from [this documentation](https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredential/getClientExtensionResults) is that `clientExtensionResults` should be optional.

Thank you

**Comment by emlun** [comment]
Hi,

The MDN documentation seems to be out of date, because [the specification defines `getClientExtensionResults()`][spec] as

>This operation returns the value of `[[clientExtensionsResults]]`, which is a map containing extension identifier → client extension output entries produced by the extension’s client extension processing.

When no extensions are used, the method returns an empty object. I suppose we could allow `null` or undefined as acceptable values in our JSON deserialization, but I also think there's value in only accepting an empty object because it makes it more difficult to forget the call to `credential.getClientExtensionResults()`. As such I'm inclined to keep it the way it is.

[spec]: https://www.w3.org/TR/webauthn/#ref-for-dom-publickeycredential-getclientextensionresults

**Comment by zafodB** [comment]
Makes sense, thanks for elaborating.
