### ISSUE TITLE
Add more abstraction

### ISSUE THREAD

**Issue by ed5s** [Yubico/java-webauthn-server#24]
Current implementation has been designed for single Relying Party without Serialisation support for security purposes. As a result we cannot use it in modern clustered (which rely on serialisation for distributed processing and caching) and multi-tenant (multiple RP) environments

In order to solve that, I propose to open the library in following the [open closed principle](https://en.wikipedia.org/wiki/Open%E2%80%93closed_principle) in introducing some abstraction in the overall design. Ideally a library API should expect a contract object (interface) in lieu of a final class.

**Comment by emlun** [comment]
Hi, thanks for your feedback!

I'm not sure what you mean cannot be done with the current implementation, though. What object(s) do you need to share between hosts? The core library as a whole, and the `RelyingParty` class in particular, are designed to have no mutable state which means that two instances constructed with the same arguments are guaranteed to behave identically. The exceptions are that two `RelyingParty` instances would generate different challenges since the two have different random number generators, and there may still be some mutable state left in the `webauthn-server-attestation` module. Still, since `RelyingParty` has no mutable state, a `PublicKeyCredentialCreationOptions` or `AssertionRequest` and its `PublicKeyCredential` response can be validated by any `RelyingParty` instance constructed with the same arguments.

I also don't understand why multi-RP environments are not supported, could you elaborate on what problems you're having?

**Comment by ed5s** [comment]
That's OK. Thanks for your detailed explanation.

**Comment by emlun** [comment]
Oh, ok. You're welcome, and you're welcome to report any other difficulties you encounter with the library - like if what I described above is not enough, or anything else.

**Comment by ed5s** [comment]
That's OK @emlun . As soon as the alpha version of my fork is working I'll send you a link to my code and I think you'll understand my initial question.
