### ISSUE TITLE
Missing `yubico-util`?

### ISSUE THREAD

**Issue by anselmoalves** [Yubico/java-webauthn-server#245]
Hi!

In my case I had to also import `yubico-util` to migrate from v1.x to v2.0 so I could import classes such as `CertificateParser`. I am not sure if this import was already required before though and but never had it. Your guide is super clear otherwise as always, thanks a lot!

**Comment by emlun** [comment]
Hi! Thanks!

Yes, that is intentional. Note that the `yubico-util` module is explicitly documented as [NOT part of the SemVer public API](https://github.com/Yubico/java-webauthn-server#semantic-versioning), and has been since release `1.8.0`, so it may receive breaking changes at any time without a major version bump. (My apologies if you're migrating from `1.7.0` or earlier, the documentation should have been better.)
