### ISSUE TITLE
Implement RS1 signature verification

### ISSUE THREAD

**Issue by azede** [Yubico/java-webauthn-server#32]
Hello,

I am looking to implement another COSE algorithm. Is there a way to add RS1 algorithm for exemple ?
Thanks

**Comment by emlun** [comment]
It should probably be possible, but the RS1 algorithm is marked as deprecated and only temporarily registered in the [COSE algorithms registry][reg]. What's the use case?

[reg]: https://www.iana.org/assignments/cose/cose.xhtml#algorithms

**Comment by azede** [comment]
Thank you for your answer, I didn't know that RS1 is deprecated.
I saw on the [fido2 server requirement](https://fidoalliance.org/specs/fido-v2.0-rd-20180702/fido-server-v2.0-rd-20180702.html#other) that this algorithm was marked as required. I wanted to implement all the required and recommended algorithms.

**Comment by emlun** [comment]
Ah, thanks for pointing that out. We should get that implemented, then. We'll work on it, but you're welcome to contribute a pull request if you like. Adding support for another algorithm looks [something like this](https://github.com/Yubico/java-webauthn-server/compare/2cb04ca3...c53008e2).

**Comment by azede** [comment]
Ok thanks, I'll see if I can contribute

**Comment by emlun** [comment]
Actually, RS1 should require little changes since the only difference from RS256 is what hash function is used. This will probably need some additional information to be passed along from [parsing the CBOR](https://github.com/Yubico/java-webauthn-server/blob/master/webauthn-server-core/src/main/java/com/yubico/webauthn/FinishAssertionSteps.java#L546-L550) to [verifying the signature](https://github.com/Yubico/java-webauthn-server/blob/master/webauthn-server-core/src/main/java/com/yubico/webauthn/FinishAssertionSteps.java#L565-L569).

I would also like a test signature from a real RS1 authenticator before pulling this into master, please let me know if you know of one.

**Comment by emlun** [comment]
Fixed in #44.
