### ISSUE TITLE
Problems with origin matching.

### ISSUE THREAD

**Issue by FlattestGuitar** [Yubico/java-webauthn-server#34]
I was building a simple app to see how the library works and I ran into an issue with the library refusing to allow through a request with the origin of `https://localhost:8080` when the rpID was set to `localhost`. Not sure if this is intended behaviour.

I had to add the exact origin to `RelyingParty.origins`, which doesn't seem like a good solution, especially considering that this has to always be set for local development. 

Perhaps a more lax matching system for the origin URIs?

I'd put this under #15, but this feels like a separate issue.

Let me know if I'm missing something obvious here.

**Comment by emlun** [comment]
Yeah, this is kind of intended, the issue is the port. The default allowed origin would be `https://localhost`, which is not exactly equal to `https://localhost:8080`. I guess we could relax the port matching, perhaps as an opt-in feature, but I think I'm more inclined to mention this particular case in the README and JavaDoc instead. What do you think?

**Comment by FlattestGuitar** [comment]
Thanks for the quick reply.

The README on its own should be enough, but it still feels odd to have to add a few lines specifically for working on an app locally. 

I doubt allowing any port to show up in the URI would cause any security issues, but I suppose it's up to you.

**Comment by emlun** [comment]
Fixed in #37, will be in version 1.5.
