### ISSUE TITLE
Dockerization of webauthn-server-demo

### ISSUE THREAD

**Issue by KyleKotowick** [Yubico/java-webauthn-server#364]
I'd like to bundle this project up into a Docker image. I've achieved this, and it runs, and the server responds to requests from _inside the container_. Even after exposing and publishing the port though, all connections from the host machine are "reset by peer".

My best guess is that this has to do with the server binding itself to only accept requests from `localhost`. I've tried setting the `YUBICO_WEBAUTHN_ALLOWED_ORIGINS=https://*:8443` env var like so, but no luck.

If my guess is correct (it's bound to `localhost`), is there a way to modify the configuration or code to bind to `0.0.0.0`?

If I'm wrong, any thoughts on what else the problem could be?

**Comment by emlun** [comment]
If you're running the application using the [`EmbeddedServer`](https://github.com/Yubico/java-webauthn-server/blob/main/webauthn-server-demo/src/main/java/demo/webauthn/EmbeddedServer.java) class rather than in an application server, then it's most likely [this line](https://github.com/Yubico/java-webauthn-server/blob/b7b589364b6e84e2e79b09fdac654747c8097d98/webauthn-server-demo/src/main/java/demo/webauthn/EmbeddedServer.java#L75) that you need to edit.

Out of curiosity, though: why do you want to dockerize the demo application?

**Comment by emlun** [comment]
(Note also that the [doc comment as of that version](https://github.com/Yubico/java-webauthn-server/blob/b7b589364b6e84e2e79b09fdac654747c8097d98/webauthn-server-demo/src/main/java/demo/webauthn/EmbeddedServer.java#L43-L46) is out of date - see #366.)

**Comment by KyleKotowick** [comment]
That worked, thanks!

We're using this project in an automated test process for a different project. Having it as a Docker image makes it much easier and faster to spin up in a CI/CD VM.
