### ISSUE TITLE
IT test with the library?

### ISSUE THREAD

**Issue by WatameBytes** [Yubico/java-webauthn-server#374]
At the moment, I made a React fronted to test the entire flow, using webautn-json. 

I was wondering if there is an easier way of testing the entire flow without me needing to make a frontend? Since we need an authenticator to sign the challenge and the domain has to be set up, so not sure how to go around to achieve this.

**Comment by emlun** [comment]
What is it you want to test? Just your backend API (internal or external), or the entire end-to-end user journey including the frontend?

The library itself is stateless, so you can have tests with hard-coded challenges and corresponding responses. If you're also including an HTTP server layer in the test, you'll need a way to inject the appropriate state into the server, but if you have that, these tests should be easy to do. See [`RelyingPartyRegistrationSpec`](https://github.com/Yubico/java-webauthn-server/blob/240b8d937e5aeb6d861625dada77035b49b839bf/webauthn-server-core/src/test/scala/com/yubico/webauthn/RelyingPartyRegistrationSpec.scala#L4456-L4483) [`RelyingPartyAssertionSpec`](https://github.com/Yubico/java-webauthn-server/blob/240b8d937e5aeb6d861625dada77035b49b839bf/webauthn-server-core/src/test/scala/com/yubico/webauthn/RelyingPartyAssertionSpec.scala#L2097-L2181) for some examples.

If you want to test a pair of challenge and response, with randomly generated challenges, you'll need to sign the challenge as part of the test. With default settings, the library doesn't verify attestation and thus doesn't require that you use any particular kind of authenticator - so in your tests you can use a software implementation of an authenticator to generate the signature. There are some [tests in the demo application that do this](https://github.com/Yubico/java-webauthn-server/blob/240b8d937e5aeb6d861625dada77035b49b839bf/webauthn-server-demo/src/test/scala/demo/webauthn/WebAuthnServerSpec.scala#L195-L219), using some utilities defined in the [`TestAuthenticator`](https://github.com/Yubico/java-webauthn-server/blob/240b8d937e5aeb6d861625dada77035b49b839bf/webauthn-server-core/src/test/scala/com/yubico/webauthn/TestAuthenticator.scala#L559) class in the core module's test suite. `TestAuthenticator` isn't exposed as part of the library API, but you're welcome to use it as inspiration if you'd like to make your own software authenticator.

Also, if you do want to require attestation, you can [configure the library with your own trust resolver](https://developers.yubico.com/java-webauthn-server/JavaDoc/webauthn-server-core/latest/com/yubico/webauthn/RelyingParty.RelyingPartyBuilder.html#attestationTrustSource(com.yubico.webauthn.attestation.AttestationTrustSource)) - so you could have your test authenticator generate its own attestation certificate and configure the server with that as a trusted attestation root certificate.

If you want to test the entire end-to-end application, you may want to try the [user agent automation for virtual authenticators](https://www.w3.org/TR/webauthn-3/#sctn-automation).

**Comment by WatameBytes** [comment]
I'm having some trouble with this and hope to get some clarification. Assume we're working directly with the actual application here, without any mocking or stubbing.

Here’s the flow we're working with for creating a Passkey:
- Start: Pass in user info to receive a challenge object.
- Sign the Challenge: (This is the step I'm struggling with.)
- Finish: Send back the signed challenge.

My main question is about step 2, signing the challenge. I don't believe this can be done within Postman alone. While I could use an external script or tool to perform the signing and manually input the signed values back into Postman, it seems that Postman itself lacks the capability for these cryptographic operations.

**Could you please provide explicit confirmation that Postman alone cannot accomplish this entire flow, given the need for a FIDO authenticator or similar functionality?** 

Just want to know if I'm wasting my time trying to accomplish the entire flow in Postman or not.

**Comment by emlun** [comment]
I've not used Postman much and it's been a long time since last I did, so I'm not at all sure about this, but it seems like Postman has some support for [scripting in a Node.js sandbox](https://learning.postman.com/docs/tests-and-scripts/write-scripts/intro-to-scripts/). This sandbox is supposed to [include the crypto-js library](https://learning.postman.com/docs/tests-and-scripts/write-scripts/postman-sandbox-api-reference/#using-external-libraries) (maybe also the native [Crypto module](https://nodejs.org/api/crypto.html)?), so it seems to me like it should be _possible_ to do this in Postman. You'd need to implement the [assertion signing procedure](https://www.w3.org/TR/2021/REC-webauthn-2-20210408/#ref-for-assertion-signature%E2%91%A7) at least. If your application requires attestation, you'll also need to implement an [attestation signing procedure](https://www.w3.org/TR/2021/REC-webauthn-2-20210408/#ref-for-attestation-object%E2%91%A8) and configure the application to trust your test attestation certificate. Beware that Web Crypto (so perhaps also crypto-js and/or node-Crypto) outputs signatures in a different format than that expected in WebAuthn, so [you may need to convert them](https://gist.github.com/philholden/50120652bfe0498958fd5926694ba354?permalink_comment_id=3744585#gistcomment-3744585).

If this cannot be done with Postman, or it's not worth the effort, then as noted above a possible workaround could be to somehow inject the challenge state into the application and then submit a hard-coded response to that challenge (one recorded manually, for example).
