### ISSUE TITLE
Support for Face/TouchID on iOS14 - Safari

### ISSUE THREAD

**Issue by DeenOub** [Yubico/java-webauthn-server#88]
Hi,

I have a fido2-server built on this library (and this is great!), and I would like to know if there is a plan to support the apple attestation format in the next versions, or how to handle it. Here is the error I get when trying to use Face/TouchID with my server.  

> Failed to resolve attestation type; unknown attestation statement format: apple

This error is returned here: 
https://github.com/Yubico/java-webauthn-server/blob/bdc1b7fa1a8c79f8250f520372f53c85070d515d/webauthn-server-core/src/main/java/com/yubico/webauthn/FinishRegistrationSteps.java#L466

I don't have this issue when using the https://demo.yubico.com/playground, so I wonder how you did resolve this!

Thanks 
Jules

**Comment by emlun** [comment]
Hi! On the one hand, the Apple attestation statement format isn't standardized yet... but it is still supposed to work as long as you don't configure `RelyingParty` to require trusted attestation, so this is a bug. Thanks for the report!

The demo site uses a different backend, so that would be why it works there.

**Comment by emlun** [comment]
This should be fixed in version `1.7.0-RC1`, which should come up on Maven Central soon. Please try it and see if that works!

**Comment by emlun** [comment]
The fix is now released in version `1.7.0`. Thanks for the report!
